import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(process.env.STOCAT_TEST_DEPS ? process.env.STOCAT_TEST_DEPS+'/package.json' : import.meta.url);
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const failures=[];
const virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>failures.push(e));
function bootstrap(window){window.HTMLMediaElement.prototype.play=function(){return Promise.resolve();};window.HTMLMediaElement.prototype.pause=function(){};window.matchMedia=()=>({matches:true});window.confirm=()=>true;window.HTMLElement.prototype.scrollIntoView=function(){};window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};window.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new window.Event('close'));};window.document.execCommand=()=>true;}
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'https://example.test/editor/',virtualConsole,beforeParse:bootstrap});
const w=dom.window,d=w.document,run=s=>w.eval(s);let passed=0;
async function test(name,fn){try{await fn();passed++;console.log('✓ '+name);}catch(e){console.error('FAIL: '+name);throw e;}}
function click(node){assert.ok(node,'Missing control');node.click();}
function makeValid(){run(`project=initialProject();project.questions.forEach((q,i)=>{q.text='Вопрос '+(i+1);q.answers=[{text:'Да',correct:true},{text:'Нет',correct:false}];});selected=project.characters[0].id;selectedQuestion=project.questions[0].id;baseline=clone(project);previewMode='scene';renderPanel();renderPreview();`);}
await test('Editor loads without JavaScript exceptions',()=>assert.equal(failures.length,0,failures.map(e=>e.message).join('\n')));
await test('Every hero starts with exactly one blank question',()=>{assert.equal(run('project.questions.length'),run('project.characters.length'));assert.equal(run('project.questions.every(q=>!q.title&&!q.text)'),true);});
await test('All eight panels render',()=>{run('for(const entry of tabs){tab=entry[0];renderPanel();}');assert.equal(d.querySelectorAll('.tab').length,8);});
await test('Clicking hero opens its question editor and live card',()=>{makeValid();click(d.querySelector('#preview .hero'));assert.equal(run('tab'),'questions');assert.equal(run('previewMode'),'question');assert.equal(d.querySelector('#preview .editor-overlay').hidden,false);assert.ok(d.querySelector('.question-editor.active'));});
await test('Question table has two columns per hero, no title fields',()=>{assert.equal(d.querySelectorAll('.qa-columns').length,6);assert.equal(d.querySelectorAll('.qa-question').length,6);assert.equal(d.querySelectorAll('.qa-answer').length,6);assert.equal(d.querySelectorAll('[data-path$=".title"]').length,0);});
await test('Typing a question updates live preview without replacing heroes',()=>{const hero=d.querySelector('#preview .hero');const input=d.querySelector('[data-path="questions.0.text"]');input.value='Найдите $\\frac{3}{4}$';input.dispatchEvent(new w.Event('input',{bubbles:true}));assert.ok(d.querySelector('#preview .editor-overlay math'));assert.ok(d.querySelector('#preview .editor-overlay').textContent.includes('Найдите'));assert.equal(d.querySelector('#preview .hero'),hero);input.dispatchEvent(new w.Event('change'));});
await test('All formulas from PDF render successfully',()=>{const formulas=[String.raw`a^2+b^2=c^2`,String.raw`\frac{a}{b}`,String.raw`\frac{x+1}{y-2}`,String.raw`\frac{3}{4}`,String.raw`x^2`,String.raw`x^{10}`,String.raw`a_n`,String.raw`a_{n+1}`,String.raw`x_1+x_2`,String.raw`\sqrt{x}`,String.raw`\sqrt{a+b}`,String.raw`\sqrt[n]{a}`,String.raw`\left( \frac{a}{b}\right)`,String.raw`\left[x+1\right]`,String.raw`\left|x\right|`,String.raw`\times`,String.raw`\cdot`,String.raw`\div`,String.raw`\pm`,String.raw`\neq`,String.raw`\leq`,String.raw`\geq`,String.raw`\infty`,String.raw`\pi`,String.raw`\approx`,String.raw`\sum_{i=1}^{n} i`,String.raw`\lim_{x \to 0} f(x)`,String.raw`25\%`,String.raw`\angle ABC`,String.raw`90^\circ`,String.raw`\triangle ABC`,String.raw`a\parallel b`,String.raw`a\perp b`,String.raw`\overline{AB}`,String.raw`\frac{-b\pm\sqrt{b^2-4ac}}{2a}`,String.raw`ax^2+bx+c=0`,String.raw`S=ab`,String.raw`P=2(a+b)`,String.raw`V=abc`,String.raw`\text{см}`,String.raw`S=24\text{ см}^2`,String.raw`v=60\text{ км/ч}`,String.raw`t=3\text{ ч}`,String.raw`\begin{cases} x+y=5 \\ x-y=1 \end{cases}`];for(const formula of formulas){const node=w.rich('p','$'+formula+'$');assert.ok(node.querySelector('math'),formula);assert.equal(node.querySelector('.formula-error'),null,formula);}});
await test('Unsafe text is not interpreted as HTML and invalid math is visible',()=>{const n=w.rich('p','<img src=x onerror=alert(1)> $\\unknowncommand{x}$');assert.equal(n.querySelector('img'),null);assert.ok(n.querySelector('.formula-error'));});
await test('Title screen can be previewed without starting a game',()=>{const select=d.querySelector('#preview-screen');select.value='title';select.dispatchEvent(new w.Event('change'));assert.ok(d.querySelector('#preview .game-card').textContent.includes(run('project.settings.title')));});
await test('Pointer click opens the question; dragging only moves the hero',()=>{run('previewMode="scene";tab="heroes";renderPanel();renderPreview();');const stage=d.querySelector('#preview .stage');stage.getBoundingClientRect=()=>({left:0,top:0,width:1200,height:750});let hero=d.querySelector('#preview .hero');hero.setPointerCapture=()=>{};hero.hasPointerCapture=()=>false;const event={button:0,clientX:200,clientY:200,pointerId:1,target:hero,preventDefault(){}};hero.onpointerdown(event);hero.onpointerup();assert.equal(run('previewMode'),'question');run('previewMode="scene";renderPreview();');hero.onpointerdown(event);hero.onpointermove({...event,clientX:240});hero.onpointerup();assert.equal(run('previewMode'),'scene');});
await test('Duplicating/deleting heroes keeps question count and content correct',()=>{run('selected=project.characters[0].id;duplicateHero();');assert.equal(run('project.questions.length'),7);assert.equal(run('new Set(project.characters.map(h=>h.questionId)).size'),7);assert.equal(run('project.questions[6].text'),run('project.questions[0].text'));run('deleteHero();');assert.equal(run('project.questions.length'),6);run('moveHistory(false);');assert.equal(run('project.questions.length'),7);run('moveHistory(true);');assert.equal(run('project.questions.length'),6);});
await test('Legacy shared questions migrate without losing question contents',()=>{run('var legacy=initialProject();legacy.questions[0].text="Сохранить меня";legacy.characters[1].questionId=legacy.characters[0].questionId;var imported=safeProject(legacy);');assert.equal(run('imported.questions.length'),6);assert.equal(run('imported.questions[1].text'),'Сохранить меня');assert.notEqual(run('imported.characters[0].questionId'),run('imported.characters[1].questionId'));});
await test('Uploaded image has red delete cross and removes only that asset',()=>{run('tab="screens";project.screens.image=catImage();renderPanel();');const remove=d.querySelector('button[aria-label="Удалить изображение: ↑ Изображение титульного экрана"]');assert.ok(remove);click(remove);assert.equal(run('project.screens.image'),'');assert.equal(run('project.characters.length'),6);});
await test('Emoji database is searchable and creates a hero plus question',()=>{w.showEmojiPicker();const search=d.querySelector('[aria-label="Поиск эмодзи"]');search.value='кошка';search.dispatchEvent(new w.Event('input'));assert.ok(d.querySelectorAll('.emoji-choice').length>0);click(d.querySelector('.emoji-choice'));assert.equal(run('project.characters.length'),7);assert.equal(run('project.questions.length'),7);assert.ok(run('project.characters[6].image').startsWith('data:image/svg+xml;base64,'));makeValid();});
await test('GIF lossless optimizer preserves frames and removes comments',()=>{const gif=Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==','base64');const comment=Buffer.from([0x21,0xfe,3,65,66,67,0]);const original=Buffer.concat([gif.subarray(0,-1),comment,gif.subarray(-1)]);const result=w.optimizeGIF(new w.Uint8Array(original));assert.deepEqual(Buffer.from(result),gif);});
await test('GIF image data survives project round trip',()=>{run('project.characters[0].image="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";var loaded=safeProject(JSON.parse(JSON.stringify(project)));');assert.equal(run('loaded.characters[0].image'),run('project.characters[0].image'));});
await test('Raster upload automatically resizes and retains the smaller encoding',async()=>{const oldImage=w.Image,oldContext=w.HTMLCanvasElement.prototype.getContext,oldData=w.HTMLCanvasElement.prototype.toDataURL;let dimensions;w.Image=class{constructor(){this.width=3200;this.height=2000;}set src(v){this.onload();}};w.HTMLCanvasElement.prototype.getContext=function(){return{drawImage:()=>{dimensions=[this.width,this.height];}};};w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/webp;base64,AA==';const file=new w.File([new Uint8Array(3000)],'large.png',{type:'image/png'});assert.equal(await w.readData(file,'image'),'data:image/webp;base64,AA==');assert.deepEqual(dimensions,[1600,1000]);w.Image=oldImage;w.HTMLCanvasElement.prototype.getContext=oldContext;w.HTMLCanvasElement.prototype.toDataURL=oldData;});
await test('Export contains no author footer or author text',()=>{const code=w.htmlGame(run('project'));assert.ok(!code.includes('Гальмиз'));assert.ok(!code.includes('game-credit'));assert.ok(d.querySelector('.editor-footer').textContent.includes('Гальмиз'));});
await test('Genially iframe isolates the whole game inside srcdoc',()=>{const code=w.embedCode(run('project'));const wrapper=new JSDOM(code).window.document.querySelector('iframe');assert.ok(wrapper.getAttribute('srcdoc').startsWith('<!doctype html>'));assert.equal(wrapper.getAttribute('sandbox'),'allow-scripts allow-modals allow-downloads');assert.ok(wrapper.getAttribute('srcdoc').includes('.game-card .action+.action'));});
await test('Compact embed code is smaller and has valid JavaScript',()=>{const regular=w.embedCode(run('project')),compact=w.embedCode(run('project'),{compact:true});assert.ok(compact.length<regular.length,`${regular.length} vs ${compact.length}`);const inner=new JSDOM(compact).window.document.querySelector('iframe').getAttribute('srcdoc');for(const m of inner.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);});
await test('Copy button copies full HTML as well as iframe code',async()=>{w.showEmbed();const mode=d.querySelector('#embed-mode');mode.value='html';mode.dispatchEvent(new w.Event('change'));let copies=0;d.execCommand=()=>{copies++;return true;};click([...d.querySelectorAll('#export-dialog button')].find(n=>n.textContent==='Копировать код'));assert.equal(copies,1);mode.value='inline';mode.dispatchEvent(new w.Event('change'));click([...d.querySelectorAll('#export-dialog button')].find(n=>n.textContent==='Копировать код'));assert.equal(copies,2);});
await test('Copy falls back to Clipboard API and handles restrictions honestly',async()=>{const area=d.querySelector('#embed-code');d.execCommand=()=>false;let copied='';Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async s=>copied=s},configurable:true});assert.equal(await w.copyCode(area),true);assert.equal(copied,area.value);Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async()=>{throw Error('denied');}},configurable:true});assert.equal(await w.copyCode(area),false);assert.ok(d.querySelector('#toast').textContent.includes('Ctrl/Cmd'));d.execCommand=()=>true;});
await test('Lighten button changes the visible Genially code instead of downloading',async()=>{const before=d.querySelector('#embed-code').value;click([...d.querySelectorAll('#export-dialog button')].find(n=>n.textContent==='Облегчить код'));await new Promise(resolve=>setTimeout(resolve,20));const after=d.querySelector('#embed-code').value;assert.ok(after.length<before.length);assert.equal(d.querySelector('#embed-code').closest('dialog').open,true);assert.ok(d.querySelector('#export-content').textContent.includes('Код в поле обновлён'));});
await test('Exported game starts without the editor or network',()=>{const child=new JSDOM(w.htmlGame(run('project'),{compact:true}),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse:bootstrap});assert.ok(child.window.document.querySelector('.game-card').textContent.includes('Начать игру'));child.window.close();});
await test('Exported formulas retain offline math renderer',()=>{run('project.questions[0].text="Вычислите $\\\\frac{3}{4}$";');const code=w.htmlGame(run('project'),{compact:true});const child=new JSDOM(code,{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse:bootstrap});child.window.document.querySelector('.action').click();child.window.document.querySelector('.hero').click();assert.ok(child.window.document.querySelector('.game-card math'));assert.equal(child.window.document.querySelector('.game-card h2'),null);child.window.close();});
await test('Compact math exports include MathML, not the whole math library',()=>{const normal=w.htmlGame(run('project')),compact=w.htmlGame(run('project'),{compact:true});assert.ok(normal.length-compact.length>200000);assert.ok(compact.includes('COMPILED_MATH'));});
await test('One correct answer leads to victory, wrong answer exhausts lives',()=>{run('var p=clone(project);p.screens.showTitle=false;p.characters=p.characters.slice(0,1);p.questions=p.questions.slice(0,1);p.settings.lives=1;var root=document.createElement("div");startGame(root,p);');const root=run('root');click(root.querySelector('.hero'));root.querySelectorAll('input')[0].checked=true;click(root.querySelector('.action'));click([...root.querySelectorAll('.action')].find(b=>b.textContent==='Продолжить'));assert.ok(root.textContent.includes('Победа!'));root._dispose();run('startGame(root,p);');click(root.querySelector('.hero'));root.querySelectorAll('input')[1].checked=true;click(root.querySelector('.action'));assert.ok(root.textContent.includes('Игра окончена'));root._dispose();});
await test('Multi, text and order answer checks preserve their behavior',()=>{assert.equal(w.answerCorrect({type:'multi',answers:[{correct:true},{correct:true},{correct:false}]},[0,1]),true);assert.equal(w.answerCorrect({type:'multi',answers:[{correct:true},{correct:true}]},[0]),false);assert.equal(w.answerCorrect({type:'text',accepted:'12\nдвенадцать',trimSpaces:true,caseSensitive:false},' ДВЕНАДЦАТЬ '),true);assert.equal(w.answerCorrect({type:'order',answers:[{},{}]},[0,1]),true);assert.equal(w.answerCorrect({type:'order',answers:[{},{}]},[1,0]),false);});
await test('Six original scene templates and three palettes are valid SVG',()=>{const seen=new Set();for(const [id] of run('BACKGROUND_THEMES'))for(const palette of ['ink','sage','sepia']){const data=w.scenePreset(id,palette),svg=Buffer.from(data.split(',')[1],'base64').toString();assert.ok(!new w.DOMParser().parseFromString(svg,'image/svg+xml').querySelector('parsererror'));assert.ok(svg.includes('viewBox="0 0 1200 750"'));assert.ok(!svg.includes('<script'));seen.add(data);}assert.equal(seen.size,18);});
await test('Selecting a background changes only scene image and supports undo',()=>{makeValid();run('tab="design";renderPanel();');const before=run('project.scene.image'),heroes=run('JSON.stringify(project.characters)');click(d.querySelector('[aria-label="Выбрать фон: Большая библиотека"]'));assert.notEqual(run('project.scene.image'),before);assert.equal(run('JSON.stringify(project.characters)'),heroes);run('moveHistory(false)');assert.equal(run('project.scene.image'),before);});
await test('All eight effects play immediately on selection and restore without changing progress',()=>{makeValid();const calls=[];const old=w.Element.prototype.animate;w.Element.prototype.animate=function(frames,options){const a={cancelled:false,cancel(){this.cancelled=true;},onfinish:null};calls.push({target:this,frames,options,a});return a;};run('tab="heroes";renderPanel();previewMode="scene";renderPreview();');for(const type of ['blink','pulse','grow','glow','color','outline','disappear','fade']){const input=d.querySelector('[data-path="characters.0.effect"]');input.value=type;input.dispatchEvent(new w.Event('input'));assert.ok(calls.length);const last=calls.at(-1);assert.equal(last.target.tagName,'IMG');assert.equal(last.options.iterations,run('project.characters[0].effectRepeat'));last.a.onfinish();run('stopEffectPreview();');assert.equal(d.querySelector('#preview .hero img').style.opacity,'');assert.ok(!d.querySelector('#preview .hero').classList.contains('found-hero'));}assert.ok(calls.length>=8);w.Element.prototype.animate=old;});
await test('Color, duration, repetition and final action each retrigger preview',()=>{const calls=[];w.Element.prototype.animate=function(frames,options){const a={onfinish:null,cancel(){}};calls.push({frames,options,a});return a;};run('tab="heroes";previewMode="scene";renderPanel();renderPreview();');for(const [property,value]of [['effectColor','#ff4466'],['effectDuration','1200'],['effectRepeat','2'],['after','hide']]){const input=d.querySelector('[data-path="characters.0.'+property+'"]');const count=calls.length;input.value=value;input.dispatchEvent(new w.Event('input'));assert.ok(calls.length>count,property);}assert.equal(calls.at(-1).options.duration,1200);assert.equal(calls.at(-1).options.iterations,2);const saved=run('JSON.stringify(project)');click([...d.querySelectorAll('#panel button')].find(n=>n.textContent==='▶ Повторить эффект'));assert.equal(run('JSON.stringify(project)'),saved);run('previewMode="question";renderEditorOverlay();');assert.equal(run('effectPreviewJob'),null);delete w.Element.prototype.animate;});
await test('Noto catalog has 881 entries and Russian search finds cats',()=>{assert.equal(w.notoEntries().length,881);w.showNotoPicker();const search=d.querySelector('[aria-label="Поиск GIF Noto"]');search.value='кот';search.dispatchEvent(new w.Event('input'));assert.ok(d.querySelectorAll('.noto-choice').length>0);assert.ok(d.querySelector('.noto-choice img').src.startsWith('https://fonts.gstatic.com/'));d.querySelector('#export-dialog').close();});
await test('Selected Noto GIF is embedded and creates exactly one hero/question',async()=>{makeValid();const bytes=Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==','base64'),old=w.fetch;let requestURL='';w.fetch=async(url)=>{requestURL=url;return{ok:true,headers:{get:()=>String(bytes.length)},arrayBuffer:async()=>new w.Uint8Array(bytes).buffer};};w.showNotoPicker();click(d.querySelector('.noto-choice'));await new Promise(resolve=>setTimeout(resolve,15));assert.ok(requestURL.endsWith('/512.gif'));assert.equal(run('project.characters.length'),7);assert.equal(run('project.questions.length'),7);assert.ok(run('project.characters[6].image').startsWith('data:image/gif;base64,'));assert.ok(run('project.characters[6].imageCredit').startsWith('Noto'));assert.ok(w.htmlGame(run('project')).includes('CC BY 4.0'));w.fetch=old;});
await test('Noto selection can replace question image without adding a hero',async()=>{w.showNotoPicker('questions.0.image');click(d.querySelector('.noto-choice'));await new Promise(resolve=>setTimeout(resolve,10));assert.equal(run('project.characters.length'),7);assert.ok(run('project.questions[0].image').startsWith('data:image/gif;base64,'));assert.ok(run('safeProject(JSON.parse(JSON.stringify(project))).questions[0].imageCredit').startsWith('Noto'));});
await test('Noto network failure stays in picker and does not modify project',async()=>{run('notoCache.clear();');const before=run('JSON.stringify(project)'),old=w.fetch;w.fetch=async()=>{throw Error('offline');};w.showNotoPicker();click(d.querySelector('.noto-choice'));await new Promise(resolve=>setTimeout(resolve,10));assert.ok(d.querySelector('#export-content [role="status"]').textContent.includes('Не удалось'));assert.equal(run('JSON.stringify(project)'),before);d.querySelector('#export-dialog').close();w.fetch=old;});
await test('Title controls belong to title sheet and size matches exported game',()=>{makeValid();run('tab="game";renderPanel();');assert.equal(d.querySelector('[data-path="settings.title"]'),null);run('tab="screens";previewMode="title";renderPanel();');const slider=d.querySelector('[data-path="screens.titleSize"]');assert.equal(slider.type,'range');slider.value='48';slider.dispatchEvent(new w.Event('input'));slider.dispatchEvent(new w.Event('change'));assert.equal(d.querySelector('#preview .game-card').style.getPropertyValue('--screen-title-size'),'48px');const child=new JSDOM(w.htmlGame(run('project'),{compact:true}),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse:bootstrap});assert.equal(child.window.document.querySelector('.game-card').style.getPropertyValue('--screen-title-size'),'48px');child.window.close();});
await test('Shared effects propagate, preserve independent settings and support undo',()=>{makeValid();run('tab="heroes";renderPanel();');const send=(path,value)=>{const input=d.querySelector('[data-path="'+path+'"]');if(input.type==='checkbox')input.checked=value;else input.value=value;input.dispatchEvent(new w.Event('input'));input.dispatchEvent(new w.Event('change'));};send('settings.effectAll',true);send('characters.0.effect','pulse');assert.equal(run('project.characters.every(h=>h.effect==="pulse")'),true);send('settings.afterAll',true);send('characters.0.after','hide');assert.equal(run('project.characters.every(h=>h.after==="hide")'),true);run('moveHistory(false)');assert.equal(run('project.characters.every(h=>h.after==="keep")'),true);send('settings.effectAll',false);send('characters.0.effect','blink');assert.equal(run('project.characters[1].effect'),'pulse');});
await test('Answer selection keeps the edited row and panel in place',()=>{makeValid();run('tab="questions";renderPanel();');const panel=d.querySelector('#panel'),row=d.querySelector('.question-editor');panel.scrollTop=280;const checks=row.querySelectorAll('.question-row input');checks[1].checked=true;checks[1].dispatchEvent(new w.Event('change'));assert.equal(d.querySelector('.question-editor'),row);assert.equal(panel.scrollTop,280);assert.equal(run('project.questions[0].answers[1].correct'),true);const type=row.querySelector('select');type.value='multi';type.dispatchEvent(new w.Event('input'));type.dispatchEvent(new w.Event('change'));assert.equal(panel.scrollTop,280);});
await test('Victory image survives import and appears in preview and runtime',()=>{makeValid();run('project.screens.winImage=catImage();project=safeProject(project);previewMode="win";renderPreview();');assert.equal(d.querySelector('#preview .question-image').src,run('project.screens.winImage'));run('var imageGame=clone(project);imageGame.screens.showTitle=false;imageGame.characters=imageGame.characters.slice(0,1);var imageRoot=document.createElement("div");startGame(imageRoot,imageGame);');const root=run('imageRoot');click(root.querySelector('.hero'));root.querySelector('input').checked=true;click(root.querySelector('.action'));click([...root.querySelectorAll('.action')].find(b=>b.textContent==='Продолжить'));assert.equal(root.querySelector('.question-image').src,run('project.screens.winImage'));root._dispose();});
await test('All eight basic sounds contain valid embedded WAV headers',()=>{const sounds=run('basicSounds()');assert.equal(Object.keys(sounds).length,8);for(const value of Object.values(sounds)){const bytes=Buffer.from(value.split(',')[1],'base64');assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.equal(bytes.toString('ascii',8,12),'WAVE');assert.equal(bytes.readUInt32LE(40),bytes.length-44);}assert.equal(Object.keys(run('safeProject(initialProject()).audio')).length,8);});
await test('Retry option is in Game settings',()=>{run('tab="game";renderPanel();');assert.equal(d.querySelector('[data-path="settings.retryWrong"]').type,'checkbox');});
await test('Wrong answers follow hero effects and only exhausted lives cause defeat in both exports',()=>{
 makeValid();
 for(const compact of [false,true])for(const retry of [false,true])for(const after of ['keep','hide','fade']){
  const p=run('clone(project)');p.screens.showTitle=false;p.settings.retryWrong=retry;p.settings.lives=2;p.settings.penalty='each';p.characters=p.characters.slice(0,2);p.characters[0].after=after;p.characters[0].effect='pulse';
  const child=new JSDOM(w.htmlGame(p,{compact}),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse:bootstrap}),doc=child.window.document;
  const answer=correct=>{const inputs=doc.querySelectorAll('.answer-item input');inputs[correct?0:1].checked=true;click([...doc.querySelectorAll('.action')].find(b=>b.textContent==='Проверить'));};
  const next=()=>click([...doc.querySelectorAll('.action')].find(b=>b.textContent==='Продолжить'));
  click(doc.querySelector('.hero'));answer(false);assert.equal(doc.querySelector('.game-card h1'),null);
  const hero=doc.querySelector('.hero'),img=hero.querySelector('img');assert.equal(img.style.opacity,after==='hide'?'0':after==='fade'? '0.25':'');assert.equal(hero.style.opacity,'1');
  if(retry){assert.equal(hero.classList.contains('found-hero'),false);assert.equal(doc.querySelector('.action').disabled,false);answer(true);}else{assert.equal(hero.classList.contains('found-hero'),true);assert.equal(doc.querySelector('.action').disabled,true);assert.equal(doc.querySelector('.action').hidden,true);assert.equal(doc.querySelector('.feedback').textContent,'Неверный ответ.');assert.deepEqual([...doc.querySelectorAll('.action')].filter(b=>!b.hidden).map(b=>b.textContent),['Продолжить']);}
  next();click(doc.querySelectorAll('.hero')[1]);answer(true);if(!retry)assert.deepEqual([...doc.querySelectorAll('.action')].filter(b=>!b.hidden).map(b=>b.textContent),['Продолжить']);next();assert.equal(doc.querySelector('h1').textContent,'Победа!');doc.querySelector('#game')._dispose();child.window.close();
  p.settings.lives=1;const loss=new JSDOM(w.htmlGame(p,{compact}),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse:bootstrap}),ld=loss.window.document;click(ld.querySelector('.hero'));ld.querySelectorAll('.answer-item input')[1].checked=true;click(ld.querySelector('.action'));assert.equal(ld.querySelector('h1').textContent,'Игра окончена');ld.querySelector('#game')._dispose();loss.window.close();
 }
});
await test('Last wrong answer without retry wins with one remaining life',()=>{makeValid();run('var lastWrong=clone(project);lastWrong.screens.showTitle=false;lastWrong.settings.retryWrong=false;lastWrong.settings.lives=2;lastWrong.characters=lastWrong.characters.slice(0,1);var lastRoot=document.createElement("div");startGame(lastRoot,lastWrong);');const root=run('lastRoot');click(root.querySelector('.hero'));root.querySelectorAll('input')[1].checked=true;click(root.querySelector('.action'));click([...root.querySelectorAll('.action')].find(b=>b.textContent==='Продолжить'));assert.equal(root.querySelector('h1').textContent,'Победа!');root._dispose();});
await test('Countdown with lives remaining ends in victory',()=>{makeValid();const p=run('clone(project)');p.screens.showTitle=false;p.settings.timer='countdown';p.settings.seconds=1;let tick;const child=new JSDOM(w.htmlGame(p,{compact:true}),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse(window){bootstrap(window);window.setInterval=fn=>{tick=fn;return 1;};}});const now=child.window.Date.now();child.window.Date.now=()=>now+2000;tick();assert.equal(child.window.document.querySelector('h1').textContent,'Победа!');child.window.document.querySelector('#game')._dispose();child.window.close();});
await test('Hover selector updates preview and survives project import and both exports',()=>{makeValid();run('tab="heroes";renderPanel();');const select=d.querySelector('[data-path="characters.0.hoverEffect"]');assert.equal(select.options.length,7);for(const value of ['none','pulse','grow','bounce','wiggle','glow','spin']){select.value=value;select.dispatchEvent(new w.Event('input'));select.dispatchEvent(new w.Event('change'));assert.equal(d.querySelector('#preview .hero').dataset.hoverEffect,value);assert.equal(run('safeProject(clone(project)).characters[0].hoverEffect'),value);for(const compact of [false,true]){const p=run('clone(project)');p.screens.showTitle=false;const child=new JSDOM(w.htmlGame(p,{compact}),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse:bootstrap});assert.equal(child.window.document.querySelector('.hero').dataset.hoverEffect,value);assert.ok(child.window.document.querySelector('style').textContent.includes('@keyframes hover-pulse'));child.window.document.querySelector('#game')._dispose();child.window.close();}}});
await test('Answer effects suppress hover without changing hero position',()=>{const node=d.createElement('button');node.className='hero';node.append(d.createElement('img'));const h=run('newHero()');h.rotation=37;h.flipX=true;w.placeHero(node,h);const before=node.style.transform,old=w.Element.prototype.animate;let animation;w.Element.prototype.animate=()=>animation={onfinish:null,cancel(){}};const stop=w.playHeroEffect(node,h,{preview:true});assert.equal(node.classList.contains('effect-playing'),true);animation.onfinish();assert.equal(node.classList.contains('effect-playing'),false);assert.equal(node.style.transform,before);stop();if(old)w.Element.prototype.animate=old;else delete w.Element.prototype.animate;});
await test('Shared hover switch applies to existing and new heroes, persists and can be disabled',()=>{makeValid();run('tab="heroes";renderPanel();');const send=(path,value)=>{const input=d.querySelector('[data-path="'+path+'"]');if(input.type==='checkbox')input.checked=value;else input.value=value;input.dispatchEvent(new w.Event('input'));input.dispatchEvent(new w.Event('change'));};assert.equal(d.querySelector('[data-path="settings.hoverAll"]').getAttribute('role'),'switch');send('characters.0.hoverEffect','bounce');send('settings.hoverAll',true);assert.equal(run('project.characters.every(h=>h.hoverEffect==="bounce")'),true);send('characters.0.hoverEffect','glow');assert.equal(run('project.characters.every(h=>h.hoverEffect==="glow")'),true);run('mutate(()=>project.characters.push(newHero(7)));');assert.equal(run('project.characters[6].hoverEffect'),'glow');assert.equal(run('safeProject(clone(project)).settings.hoverAll'),true);send('settings.hoverAll',false);send('characters.0.hoverEffect','spin');assert.equal(run('project.characters[1].hoverEffect'),'glow');run('moveHistory(false)');assert.equal(run('project.characters[0].hoverEffect'),'glow');});
await test('Full-window exports resize the complete background and keep credits inside the game',()=>{makeValid();for(const compact of [false,true]){const p=run('clone(project)');p.screens.showTitle=false;p.screens.imageCredit='Noto test';let width=1440,height=900,resize,disconnected=0;const child=new JSDOM(w.htmlGame(p,{compact}),{runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse(window){bootstrap(window);window.HTMLElement.prototype.getBoundingClientRect=()=>({width,height});window.ResizeObserver=class{constructor(fn){resize=fn;}observe(){}disconnect(){disconnected++;}};}}),doc=child.window.document,bg=doc.querySelector('.backdrop'),hero=doc.querySelector('.hero');assert.equal(bg.style.width,'1200px');assert.equal(bg.style.height,'750px');assert.equal(bg.style.transform,'scale(1.2,1.2)');const left=hero.style.left,top=hero.style.top;width=600;height=1000;resize();assert.equal(bg.style.transform,'scale(0.5,1.3333333333333333)');assert.equal(hero.style.left,left);assert.equal(hero.style.top,top);assert.equal(child.window.getComputedStyle(doc.querySelector('.animation-credits')).position,'absolute');assert.ok(doc.querySelector('style').textContent.includes('#game>.stage{width:100%;height:100%;aspect-ratio:auto!important}'));click(hero);assert.ok(doc.querySelector('.answer-list'));doc.querySelector('#game')._dispose();assert.equal(disconnected,1);child.window.close();}});
await test('No unexpected script failures occurred',()=>assert.equal(failures.length,0,failures.map(e=>e.message).join('\n')));
dom.window.close();
console.log(`\n${passed} checks passed. Real browser and Genially visual checks remain separate.`);
